@startuml seqeunce

actor "Student" as S
participant "System" as Sys
database "Database" as D

S -> Sys: 1. Write sign up information
Sys -> D: 2. Save sign up information
D --> Sys: 3. Return sign up result
Sys --> S: 4. Return sign up result
S -> Sys: 5. Set up profile
Sys -> D: 6. Save profile
D --> Sys: 7. Return profile result
Sys --> S: 8. Return profile result

@enduml
