@startuml seqeunce

actor "User" as U
participant "System" as S
database "Firebase" as F

U -> S: Request resetting password
S -> F: Request resetting password
F -> U: Send email to user
U -> F: Rest password

@enduml
