@startuml seqeunce03

participant "SignInPage" as SignInPage
participant "PasswordResetPage" as PasswordResetPage
database "Firebase" as Firebase

SignInPage -> PasswordResetPage: 1. click password reset button
PasswordResetPage -> Firebase: 2. request send email
Firebase --> PasswordResetPage:
PasswordResetPage --> SignInPage:

@enduml
