@startuml seqeunce04

participant "MyprofilePage" as MyProfilePage
participant "EventCreatePage" as EventCreatePage
database "Firebase" as Firebase

MyProfilePage -> EventCreatePage: 1. click create button
EventCreatePage -> EventCreatePage: 2. validate event info
EventCreatePage -> Firebase: 3. store event data
Firebase --> EventCreatePage:
EventCreatePage --> MyProfilePage:


@enduml
