@startuml seqeunce04
actor "User 1" as U1
participant "Chat" as C
database "Firebase" as F
actor "User 2" as U2

U1 -> C: 1. Input message
C -> F: 2. Add message data
F -> C: 3. Recognize changed message
C -> U2: 4. Display message
C -> U1: 4. Display message

@enduml
