@startuml seqeunce05

actor "User" as U
participant "System" as S
database "Firebase" as F

U -> S: 1. Request resetting password
S -> F: 2. Request resetting password
F -> U: 3. Send email to user
U -> F: 4. Rest password

@enduml
